"""Add email_addr_hash and rename email to encrypted_email_addr

Revision ID: 5db9b6dfa291
Revises: a3f8e396394d
Create Date: 2026-04-22 11:31:33.749676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db9b6dfa291'
down_revision = 'a3f8e396394d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email', new_column_name='encrypted_email_addr', existing_type=sa.LargeBinary)
        batch_op.add_column(sa.Column('email_addr_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_addr_hash')
        batch_op.alter_column('encrypted_email_addr', new_column_name='email', existing_type=sa.LargeBinary)

    # ### end Alembic commands ###
