"""empty message

Revision ID: 8e2043c49ed0
Revises: 
Create Date: 2026-03-27 13:42:42.675900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2043c49ed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed_requested', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seed_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seeded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('seeded_at')
        batch_op.drop_column('seed_version')
        batch_op.drop_column('seed_requested')

    # ### end Alembic commands ###
