"""Add password reset fields and rename confirmation_sent_at to confirmation_email_sent_at

Revision ID: a3f8e396394d
Revises: c7e864b84930
Create Date: 2026-04-21 22:33:12.586121

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a3f8e396394d'
down_revision = 'c7e864b84930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=64), nullable=True))
        batch_op.alter_column('confirmation_sent_at', new_column_name='confirmation_email_sent_at', existing_type=sa.DateTime)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirmation_email_sent_at', new_column_name='confirmation_sent_at', existing_type=sa.DateTime)
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_email_sent_at')

    # ### end Alembic commands ###
