"""Add price column to DailyLogItem

Revision ID: a9b15113721d
Revises: b723dab88d91
Create Date: 2026-04-05 03:49:31.487254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b15113721d'
down_revision = 'b723dab88d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log_item', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
