"""Adding DailyLogItem

Revision ID: b723dab88d91
Revises: 7c50f7b28d94
Create Date: 2026-04-02 17:32:47.472989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b723dab88d91'
down_revision = '7c50f7b28d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_log_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('nutrition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nutrition_id'], ['nutrition.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_log_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_item_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_item_date'))

    op.drop_table('daily_log_item')
    # ### end Alembic commands ###
