"""Add food_id to daily_log_item and make that and recipe_id nullable

Revision ID: c7e864b84930
Revises: 4c7d9e12aa31
Create Date: 2026-04-09 18:05:16.319801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7e864b84930'
down_revision = '4c7d9e12aa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_id', sa.Integer(), nullable=True))
        batch_op.alter_column('recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('food_id')

    # ### end Alembic commands ###
