"""Added user_id column to Ingredient and Nutrition tables

Revision ID: cec5f2cbb54d
Revises: 8e2043c49ed0
Create Date: 2026-03-28 17:24:14.154230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec5f2cbb54d'
down_revision = '8e2043c49ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as nullable first
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # 2. Backfill existing rows (MUST be outside a batch_op block)
    op.execute("UPDATE nutrition SET user_id = 3 WHERE user_id IS NULL")
    op.execute("UPDATE ingredient SET user_id = 3 WHERE user_id IS NULL")

   # 3. Apply constraints in a second batch block
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.alter_column('user_id', 
                            existing_type=sa.Integer(), # CRITICAL FOR MYSQL
                            nullable=False)
        batch_op.create_foreign_key('fk_nutrition_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('user_id', 
                            existing_type=sa.Integer(), # CRITICAL FOR MYSQL
                            nullable=False)
        batch_op.create_foreign_key('fk_ingredient_user', 'user', ['user_id'], ['id'])


def downgrade():
    # 1. Revert changes to 'nutrition'
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        # Use the name you defined in upgrade, or None if you kept it as None
        batch_op.drop_constraint('fk_nutrition_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # 2. Revert changes to 'ingredient'
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ingredient_user', type_='foreignkey')
        # Note: If user_id already existed before this migration, 
        # do NOT drop the column here—only drop the constraint.

    # ### end Alembic commands ###
