"""empty message

Revision ID: 4162452711e6
Revises: c3d8f5a1b6e7
Create Date: 2026-10-03 02:23:09.780459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4162452711e6'
down_revision = 'c3d8f5a1b6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=False)

    with op.batch_alter_table('nutrition_alternative', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_nutrition_alternative_primary'))
        batch_op.drop_constraint(batch_op.f('nutrition_alternative_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('nutrition_alternative_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'nutrition', ['nutrition_id'], ['id'])
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'])
        batch_op.drop_column('primary_food_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_alternative', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_food_id', mysql.INTEGER(), sa.Computed('((case when (`is_primary` = 1) then `food_id` else NULL end))', persisted=False), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('nutrition_alternative_ibfk_1'), 'food', ['food_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('nutrition_alternative_ibfk_2'), 'nutrition', ['nutrition_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('uq_nutrition_alternative_primary'), ['primary_food_id'], unique=True)

    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=True)

    # ### end Alembic commands ###
