"""Added size fields to recipe

Revision ID: ba1ab84b3423
Revises: e2f4c6a8b0d2
Create Date: 2026-07-05 14:09:43.489446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba1ab84b3423'
down_revision = 'e2f4c6a8b0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_source_fdc_id'))

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_oz', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('size_g', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_addr_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_user_oauth'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_oauth'), ['oauth_provider', 'oauth_id'], unique=True)
        batch_op.alter_column('email_addr_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('size_g')
        batch_op.drop_column('size_oz')

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_source_fdc_id'), ['source', 'fdc_id'], unique=True)

    # ### end Alembic commands ###
